theme: jekyll-theme-minimal
logo: img/MDaveyHeadshot.jpeg 
title: Marshall Davey
description: I am a postdoctoral research associate in Mathematics Department at the University of North Carolina at Chapel Hill.
