theme: jekyll-theme-minimal
logo: img/MDaveyHeadshot.jpeg 
title: Marshall Davey
description: I am a postdoctoral research associate in the University of North Carolina at Chapel Mathematics Department.
